### ISSUE TITLE
Using mqlight with node 6 causes error on 'send'

### ISSUE THREAD

**Issue by ivanovivelin** [mqlight/nodejs-mqlight#1]
`Error: Algorithm "sha1"  not supported. supported values: passthrough
   at applyDefaults (/Users/ivelinivanov/Documents/dmt-test/dmt-module/node_modules/object-hash/index.js:89:11)
   at objectHash (/Users/ivelinivanov/Documents/dmt-test/dmt-module/node_modules/object-hash/index.js:31:13)
   at createLink (/Users/ivelinivanov/Documents/dmt-test/dmt-module/node_modules/amqp10-link-cache/index.js:25:18)
   at AMQPClient.Client.createSender (/Users/ivelinivanov/Documents/dmt-test/dmt-module/node_modules/amqp10-link-cache/index.js:104:14)
   at Client.send (/Users/ivelinivanov/Documents/dmt-test/dmt-module/node_modules/mqlight/mqlight.js:2624:13)
   at mqsend (/Users/ivelinivanov/Documents/dmt-test/dmt-module/server/routes/common/mqsdr.js:51:18)
   at module.exports (/Users/ivelinivanov/Documents/dmt-test/dmt-module/server/config/login-openid.js:32:5)`

Getting this error if I use mqlight and try to send a message running on node 6.9.1 This issue does not exist on node 4 ...

**Comment by dnwe** [comment]
@IIvanov8888 hmm, I wonder - are you using the collections module and hitting https://github.com/montagejs/collections/issues/162 / https://github.com/puleos/object-hash/issues/41#issuecomment-264333083 ?

**Comment by ivanovivelin** [comment]
@dnwe nope, that does not seem to be the case. I do not use that module. It basically fails here on node 6.9 , but works fine on node 4.x  : 

```javascript
function mqsend(channel: any, mqObj: any) {
    if (mqClient && mqClient.state === 'started') {
        mqClient.send(channel, mqObj, (err: any, data: any) => {
            if (err) {
                slack.message('$mqsdr.ts - mqsend() => ' + err);
                console.log(`mgsdr.ts - mqsend() - failed reason: ${err}`);
            } else {
                console.log('mgsdr.ts - mqsend() - successful');
            }
        });
    }
}
```

**Comment by ivanovivelin** [comment]
I had to require the mq in app.js before I try to send something, it had to wait , no idea why it is issue only on node 6 + . Closing the issue
