### ISSUE TITLE
MQ Authenticate enabled used os and mqlight v2.0 with Node JS v6 can't connected ?

### ISSUE THREAD

**Issue by adhasyuhada** [mqlight/nodejs-mqlight#6]
I want to test connection via amqp from sample code mqlight

```
     // Receive:
     var mqlight = require('mqlight');
     var recvClient = mqlight.createClient({service: 'amqp://user:user@localhost:5672'});
     recvClient.on('started', function() {
     recvClient.subscribe('TEST/#','shared1');
     recvClient.on('message', function(data, delivery) {
               console.log(data);
          });
     });
     
     // Send:
      var sendClient = mqlight.createClient({service: 'amqp://user:user@localhost:5672'});
      sendClient.on('started', function() {
          sendClient.send('TEST/');
     });
```

i run the sample code mqlight 2.0 with node js v6

   ```
  $node mqlight_sample.js
     
         events.js:160
               throw er; // Unhandled 'error' event
           ^
     SecurityError: AMQXR0100E: A connection from 172.17.0.1 was not authorized.
         at lookupError (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/mqlight/mqlight.js:1034:11)
         at AMQPClient.<anonymous> (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/mqlight/mqlight.js:1925:13)
         at emitOne (events.js:96:13)
         at AMQPClient.emit (events.js:188:7)
         at Connection.<anonymous> (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/amqp10/lib/amqp_client.js:388:10)
         at emitOne (events.js:96:13)
         at Connection.emit (events.js:188:7)
         at Connection._processCloseFrame (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/amqp10/lib/connection.js:495:10)
         at Connection._receiveAny (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/amqp10/lib/connection.js:423:12)
         at Connection._receiveData (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/amqp10/lib/connection.js:357:8)
         at NetTransport.<anonymous> (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/amqp10/lib/connection.js:515:38)
         at emitOne (events.js:96:13)
         at NetTransport.emit (events.js:188:7)
         at Socket.<anonymous> (/media/anonim/Data/PROJECT/BTPN/btpn-mqsetup/mqlight/node_modules/amqp10/lib/transport/net_transport.js:26:49)
         at emitOne (events.js:96:13)
         at Socket.emit (events.js:188:7)
```

this one error log from MQ Server 

```
     # tail -100f /var/mqm/qmgrs/QM1/errors/amqp_0.log
     
     3/31/17 19:14:44.115  AMQXR0041E: A connection was not authorized for channel SYSTEM.DEF.AMQP received from 172.17.0.1. MQRC 2035 MQRC_NOT_AUTHORIZED
     3/31/17 19:14:45.142  AMQXR0041E: A connection was not authorized for channel SYSTEM.DEF.AMQP received from 172.17.0.1. MQRC 2035 MQRC_NOT_AUTHORIZED
```

actually authenticate for AMQP is enabled if CONNAUTH and CHCKCLNT required changed to disabled i can connected with Node JS 6
```

     START SERVICE(SYSTEM.AMQP.SERVICE)
     SET CHLAUTH(SYSTEM.DEF.AMQP) TYPE(BLOCKUSER) USERLIST('nobody')
     SET CHLAUTH(SYSTEM.DEF.AMQP) TYPE(ADDRESSMAP) ADDRESS(*) USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
     REFRESH SECURITY TYPE(CONNAUTH)
     START CHANNEL(SYSTEM.DEF.AMQP)
     DISPLAY CHSTATUS(SYSTEM.DEF.AMQP) CHLTYPE(AMQP)
```

**Comment by dnwe** [comment]
@adhasyuhada to understand exactly why the queue manager has failed to authorise the MQ Light client you need to look in the queue manager log (AMQERRxx.log) which is in /var/mqm/qmgrs/QM1/errors. The queue manager logs more detailed information about why a client was refused a connection.

**Comment by adhasyuhada** [comment]
Hi @dnwe below the error log from /var/mqm/qmgrs/QM1/errors/AMQERR01.LOG
i think maybe the mechanism to define user and password different between mqlight v1.0 and mqlight v2.0 ? this snippet code using Node JS v6 and mqlight v2 if i used Node JS v4.x and mqlight v1.0 work as well there is not error.

```
04/02/17 07:10:16 - Process(587.6) User(mqm) Program(java)
                    Host(770e29171038) Installation(Installation1)
                    VRMF(9.0.1.0) QMgr(QM1)
                   
AMQ5534: User ID 'user' authentication failed

EXPLANATION:
The user ID and password supplied by the 'AMQP' program could not be
authenticated. 
Additional information: 'N/A'.
ACTION:
Ensure that the correct user ID and password are provided by the application.
Ensure that the authentication repository is correctly configured. Look at
previous error messages for any additional information.
----- amqzfuca.c : 4486 -------------------------------------------------------
04/02/17 07:10:16 - Process(587.6) User(mqm) Program(java)
                    Host(770e29171038) Installation(Installation1)
                    VRMF(9.0.1.0) QMgr(QM1)
                   
AMQ5542: The failed authentication check was caused by the queue manager
CONNAUTH CHCKCLNT(REQDADM) configuration.

EXPLANATION:
The user ID 'user' and its password were checked because the queue manager
connection authority (CONNAUTH) configuration refers to an authentication
information (AUTHINFO) object named 'USE.OS' with CHCKCLNT(REQDADM). 

This message accompanies a previous error to clarify the reason for the user ID
and password check.
ACTION:
Refer to the previous error for more information. 

Ensure that a password is specified by the client application and that the
password is correct for the user ID. The authentication configuration of the
queue manager connection determines the user ID repository. For example, the
local operating system user database or an LDAP server. 

If the CHCKCLNT setting is OPTIONAL, the authentication check can be avoided by
not passing a user ID across the channel. For example, by omitting the MQCSP
structure from the client MQCONNX API call. 

To avoid the authentication check, you can amend the authentication
configuration of the queue manager connection, but you should generally not
allow unauthenticated remote access.
-------------------------------------------------------------------------------
04/02/17 07:10:17 - Process(587.6) User(mqm) Program(java)
                    Host(770e29171038) Installation(Installation1)
                    VRMF(9.0.1.0) QMgr(QM1)
                   
AMQ5534: User ID 'user' authentication failed

EXPLANATION:
The user ID and password supplied by the 'AMQP' program could not be
authenticated. 
Additional information: 'N/A'.
ACTION:
Ensure that the correct user ID and password are provided by the application.
Ensure that the authentication repository is correctly configured. Look at
previous error messages for any additional information.
----- amqzfuca.c : 4486 -------------------------------------------------------
04/02/17 07:10:17 - Process(587.6) User(mqm) Program(java)
                    Host(770e29171038) Installation(Installation1)
                    VRMF(9.0.1.0) QMgr(QM1)
                   
AMQ5542: The failed authentication check was caused by the queue manager
CONNAUTH CHCKCLNT(REQDADM) configuration.

EXPLANATION:
The user ID 'user' and its password were checked because the queue manager
connection authority (CONNAUTH) configuration refers to an authentication
information (AUTHINFO) object named 'USE.OS' with CHCKCLNT(REQDADM). 

This message accompanies a previous error to clarify the reason for the user ID
and password check.
ACTION:
Refer to the previous error for more information. 

Ensure that a password is specified by the client application and that the
password is correct for the user ID. The authentication configuration of the
queue manager connection determines the user ID repository. For example, the
local operating system user database or an LDAP server. 

If the CHCKCLNT setting is OPTIONAL, the authentication check can be avoided by
not passing a user ID across the channel. For example, by omitting the MQCSP
structure from the client MQCONNX API call. 

To avoid the authentication check, you can amend the authentication
configuration of the queue manager connection, but you should generally not
allow unauthenticated remote access.
-------------------------------------------------------------------------------

```

**Comment by dnwe** [comment]
@adhasyuhada did you manage to resolve your server-side problem with pmr and/or support?

**Comment by adhasyuhada** [comment]
Yes i did
